
### CONFIGURATION
##  These are settings used in the script.
##  They can all be used on the command-line, with the same name.
config:
  width:           47                         # Maximum width/columns of window inside terminal
  height:          7                          # Maximum height/lines of window inside terminal
  shell:           '/bin/bash'                # Shell used to execute keybinding commands, set to 'false' to execute command directly
  text-padding:    4                          # Padding of input for each line
  exec-background: 'true'                     # Execute command in background
  borderless:      'false'                    # Don't draw borders

### CONSTANTS
##  Variables that can be used with '@' inside this config.
##  Constants can be used anywhere in your config and from the command-line.
constants:
  terminal:          'termite'
  browser:           'firefox'
  editor:            'vim'

### KEYBINDINGS
##  Here you can define your keybindings.
##  The keystroke combination to activate them is their key,
##  and their value is the shell script that will be executed.
keybindings:
  ## BASE
  q:  'true'                                  # quit ShortStrokes program, basically do nothing

  ## OPEN applications
  ot: '@terminal'                             # Open terminal emulator
  of: '@browser --new-window'                 # Open browser

  ## OPEN web pages
  Od: '@browser https://duckduckgo.com/'      # Open DuckDuckGo
  Ow: '@browser https://wiki.archlinux.org/'  # Open Arch Linux Wiki

  ## EDIT (config) files
  ee: '@terminal --exec "@editor ~/.config/shortstrokes/config.yml"'  # Edit config file
  eE: '@terminal --exec "@editor @SHORTSTROKES_ROOT/config.yml"'      # Edit THIS config file
  eb: '@terminal --exec "@editor ~/.bashrc"'      # Edit bashrc
  ev: '@terminal --exec "@editor ~/.vimrc"'       # Edit vimrc

