
### CONFIGURATION
##  These are settings used in the script.
##  They can all be used on the command-line, with the same name.
config:
  width:           47                         # Maximum width/columns of window inside terminal
  height:          7                          # Maximum height/lines of window inside terminal
  shell:           '/bin/bash -i'             # Shell used to execute keybinding commands, set to 'false' to execute command directly
  text-padding:    4                          # Padding of input for each line
  exec-background: 'true'                     # Execute command in background
  borderless:      'false'                    # Don't draw borders when set to 'true'

### CONSTANTS
##  Variables that can be used with '@' inside this config.
##  Constants can be used anywhere in your config, except in this 'constants' section.
##  They can also be used in options from the command-line.
constants:
  terminal: 'termite'
  browser:  'firefox'
  editor:   'vim'
  scripts:  '@SHORTSTROKES_ROOT/scripts'

### KEYBINDINGS
##  Here you can define your keybindings.
##  The keystroke combination to activate them is their key,
##  and their value is the shell script that will be executed.
keybindings:
  ## BASE
  q:  'true'                                  # quit ShortStrokes program, basically do nothing

  ## OPEN applications
  ot: '@terminal'                             # Open terminal emulator
  of: '@browser --new-window'                 # Open browser

  ## OPEN web pages
  Od: '@browser https://duckduckgo.com/'      # Open DuckDuckGo
  Ow: '@browser https://wiki.archlinux.org/'  # Open Arch Linux Wiki

  ## EDIT (config) files
  ee: '@scripts/run.rb edit "~/.config/shortstrokes/config.yml" --terminal "@terminal" --shell "@SHELL" --editor "@EDITOR"'  # Edit config file
  eE: '@scripts/run.rb edit "@SHORTSTROKES_ROOT/config.yml"     --terminal "@terminal" --shell "@SHELL" --editor "@EDITOR"'  # Edit THIS config file
  eb: '@scripts/run.rb edit "~/.bashrc"                         --terminal "@terminal" --shell "@SHELL" --editor "@EDITOR"'  # Edit bashrc
  ev: '@scripts/run.rb edit "~/.vimrc"                          --terminal "@terminal" --shell "@SHELL" --editor "@EDITOR"'  # Edit vimrc
  # This repo includes a scripts directory which currently contains one script:
  # scripts/run.rb
  # It's for easier use of running commands or edditing files
  # in specific shell in new terminal emulator
  # so you don't need to play around with the weird syntax and
  # escape sequences when writing the shell commands yourself.
  # Check scripts/run.rb --help for some more info.

